// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type tcpRetransmitU64 uint64

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tcpRetransmitMapRetransmitCount         = "retransmit_count"
	tcpRetransmitProgKprobeTcpRetransmitSkb = "kprobe_tcp_retransmit_skb"
)

// loadTcpRetransmit returns the embedded CollectionSpec for tcpRetransmit.
func loadTcpRetransmit() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpRetransmitBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpRetransmit: %w", err)
	}

	return spec, err
}

// loadTcpRetransmitObjects loads tcpRetransmit and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpRetransmitObjects
//	*tcpRetransmitPrograms
//	*tcpRetransmitMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpRetransmitObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpRetransmit()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpRetransmitSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpRetransmitSpecs struct {
	tcpRetransmitProgramSpecs
	tcpRetransmitMapSpecs
	tcpRetransmitVariableSpecs
}

// tcpRetransmitProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpRetransmitProgramSpecs struct {
	KprobeTcpRetransmitSkb *ebpf.ProgramSpec `ebpf:"kprobe_tcp_retransmit_skb"`
}

// tcpRetransmitMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpRetransmitMapSpecs struct {
	RetransmitCount *ebpf.MapSpec `ebpf:"retransmit_count"`
}

// tcpRetransmitVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpRetransmitVariableSpecs struct {
}

// tcpRetransmitObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpRetransmitObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpRetransmitObjects struct {
	tcpRetransmitPrograms
	tcpRetransmitMaps
	tcpRetransmitVariables
}

func (o *tcpRetransmitObjects) Close() error {
	return _TcpRetransmitClose(
		&o.tcpRetransmitPrograms,
		&o.tcpRetransmitMaps,
	)
}

// tcpRetransmitMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpRetransmitObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpRetransmitMaps struct {
	RetransmitCount *ebpf.Map `ebpf:"retransmit_count"`
}

func (m *tcpRetransmitMaps) Close() error {
	return _TcpRetransmitClose(
		m.RetransmitCount,
	)
}

// tcpRetransmitVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpRetransmitObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpRetransmitVariables struct {
}

// tcpRetransmitPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpRetransmitObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpRetransmitPrograms struct {
	KprobeTcpRetransmitSkb *ebpf.Program `ebpf:"kprobe_tcp_retransmit_skb"`
}

func (p *tcpRetransmitPrograms) Close() error {
	return _TcpRetransmitClose(
		p.KprobeTcpRetransmitSkb,
	)
}

func _TcpRetransmitClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpretransmit_arm64_bpfel.o
var _TcpRetransmitBytes []byte
